# Generated by Django 6.0.5 on 2026-05-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
